services:
  gateway:
    container_name: gateway
    image: nginx:latest
    ports:
      - 80:80
      - 443:80
    restart: unless-stopped
    networks:
      - pro_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/:/etc/nginx/
      - /data/:/data/
    tty: true
networks:
  pro_net:
    external: true
