version: "3"

services:
  vanblog:
    container_name: "xlog"
    # 阿里云镜像源
    # image: registry.cn-beijing.aliyuncs.com/mereith/van-blog:latest
    image: mereith/van-blog:latest
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      # 邮箱地址，用于自动申请 https 证书
      EMAIL: ""
    volumes:
      # 图床文件的存放地址，按需修改。
      - /var/lib/vanblog/static:/app/static
        # 日志文件
      - /var/lib/vanblog/log:/var/log
        # Caddy 配置存储
      - /var/lib/vanblog/caddy/config:/root/.config/caddy
        # Caddy 证书存储
      - /var/lib/vanblog/caddy/data:/root/.local/share/caddy
    ports:
      - 6109:80
    networks:
      - pronet
  mongo:
    container_name: "blog-mongo"
    # 某些机器不支持 avx 会报错，所以默认用 v4 版本。有的话用最新的。
    image: mongo:4.4.16
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /var/lib/vanblog/mongo:/data/db
    networks:
      - pronet

networks:
  pronet:
    name: pro_net
    external: true
