version: "3.0"
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /var/lib/memos/:/var/opt/memos
    ports:
      - 5230:5230
