global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'brpc'
    metrics_path: /brpc_metrics
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'alloy'
    metrics_path: /api/v0/component/prometheus.exporter.process.process/metrics
    static_configs:
      - targets: ['alloy:12345']


remote_write:
  - url: 'https://prometheus-prod-18-prod-ap-southeast-0.grafana.net/api/prom/push'
    basic_auth:
      username: 'username'
      password: 'api key'
