version: "3.8"
networks:
  pro_net:
    external: true
volumes:
  prometheus_data: {}
services:
  alloy:
    container_name: alloy
    image: grafana/alloy
    restart: unless-stopped
    volumes:
      - /proc:/proc
      - /var/lib/monitor/alloy/config:/etc/alloy/:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/monitor/alloy/data:/var/lib/alloy
    ports:
      - 12345:12345
    networks:
      - pro_net
    tty: true
    environment: []
    entrypoint:
      - alloy
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    # ports:    don't have to enable access from remote
    #   - "9100:9100"
    expose:
      - 9100
    networks:
      - pro_net
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    volumes:
      - /var/lib/monitor/alertmanager/config:/etc/alertmanager
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9093:9093
    expose:
      - 9093
    networks:
      - pro_net
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - 9091:9091
    networks:
      - pro_net
    labels:
      org.label-schema.group: monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: 0:0
    restart: unless-stopped
    volumes:
      - /var/lib/monitor/prometheus/config:/etc/prometheus/
      - /var/lib/monitor/prometheus/data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    ports:
      # don't have to enable access from remote
      - 9090:9090
    expose:
      - 9090
    networks:
      - pro_net
    depends_on: []
