version: "3"
services:
  # --- CONTROL PANEL ---
  apollo-portal:
    container_name: apollo-portal
    image: apolloconfig/apollo-portal
    restart: unless-stopped
    ports:
      - 20101:8070
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://apollo-portal-mysql:3306/ApolloPortalDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: apollo
      APOLLO_PORTAL_ENVS: dev,pro
      DEV_META: http://apollo-dev-config-service:8080
      PRO_META: http://apollo-pro-config-service:8080
    depends_on:
      - apollo-portal-mysql
      - apollo-dev-config-service
      - apollo-dev-admin-service
      - apollo-pro-config-service
      - apollo-pro-admin-service
  apollo-portal-mysql:
    container_name: apollo-portal-mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: apollo
    volumes:
      - /var/lib/apollo/portal/mysql:/var/lib/mysql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 5s
      timeout: 1s
      retries: 10
  # --- DEV ---
  apollo-dev-admin-service:
    container_name: apollo-dev-admin-service
    image: apolloconfig/apollo-adminservice
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://apollo-dev-mysql:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: apollo
    volumes:
      - /var/lib/apollo/dev/admin/logs:/opt/logs
    depends_on:
      - apollo-dev-config-service
      - apollo-dev-mysql
  apollo-dev-config-service:
    container_name: apollo-dev-config-service
    image: apolloconfig/apollo-configservice
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://apollo-dev-mysql:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: apollo
    volumes:
      - /var/lib/apollo/dev/config/logs:/opt/logs
    depends_on:
      - apollo-dev-mysql
  apollo-dev-mysql:
    container_name: apollo-dev-mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: apollo
    volumes:
      - /var/lib/apollo/dev/mysql:/var/lib/mysql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 5s
      timeout: 1s
      retries: 10
  # --- PRO ---
  apollo-pro-admin-service:
    container_name: apollo-pro-admin-service
    image: apolloconfig/apollo-adminservice
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://apollo-pro-mysql:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: apollo
    volumes:
      - /var/lib/apollo/pro/admin/logs:/opt/logs
    depends_on:
      - apollo-pro-config-service
      - apollo-pro-mysql
  apollo-pro-config-service:
    container_name: apollo-pro-config-service
    image: apolloconfig/apollo-configservice
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      SPRING_DATASOURCE_URL: jdbc:mysql://apollo-pro-mysql:3306/ApolloConfigDB?characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: apollo
    volumes:
      - /var/lib/apollo/pro/config/logs:/opt/logs
    depends_on:
      - apollo-pro-mysql
  apollo-pro-mysql:
    container_name: apollo-pro-mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      #MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: apollo
    volumes:
      - /var/lib/apollo/pro/mysql:/var/lib/mysql
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 5s
      timeout: 1s
      retries: 10
networks:
  default:
    external:
      name: pro_net
