# xpansync
version: "3"

services:
  xpansync:
    container_name: "xpansync"
    build: .
    restart: "unless-stopped"
    working_dir: /app
    environment:
      GOPROXY: https://goproxy.cn
    ports:
        - "1425:1425"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/lib:/var/lib"
    entrypoint: "/app/xpansync"
    tty: true
    networks:
      - pro_net

networks:
  pro_net:
    external: true
