# xpansync

services:
  xpansync:
    container_name: "xpansync"
    build: .
    working_dir: /app
    environment:
      GOPROXY: https://goproxy.cn
      GIN_MODE: release
    ports:
        - "1425:1425"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/lib:/var/lib"
    entrypoint: "/app/xpansync"
    tty: true