FROM {{.FrontendImage}} AS ui-builder
WORKDIR /app
COPY . . 
ARG BASEPATH="/"
RUN cd ui/ && npm config set registry https://registry.npmmirror.com \
    && npm install && npm run build -- --base=$BASEPATH


FROM {{.BackendImage}} AS server-builder
WORKDIR /app
COPY . .
COPY --from=ui-builder /app/ui/dist/ /app/server/public
ENV GOPROXY=https://goproxy.cn
RUN cd server/ && ls -la && go mod tidy && go build


FROM alpine:latest
WORKDIR /app
ARG BASEPATH="/"
ENV BASEPATH=$BASEPATH
ENV TZ="Asia/Shanghai"
RUN apk --no-cache --no-progress add \
    #ca-certificates \
    tzdata && \
    cp "/usr/share/zoneinfo/$TZ" /etc/localtime && \
    echo "$TZ" >  /etc/timezone 
COPY --from=server-builder /app/server/{{.Project}} /app/{{.Project}}

VOLUME ["/app/data"]
