# xpansync
services:
  xpansync:
    container_name: xpansync
    image: jovanx/xpansync:latest
    restart: unless-stopped
    working_dir: /app
    environment:
      GOPROXY: https://goproxy.cn
      GIN_MODE: release
      BASEURL: /xpansync
    ports:
      - 1425:1425
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data:/data:ro
      - /home:/home:ro
      - /var/lib:/var/lib
    entrypoint: /app/xpansync
    tty: true
    networks:
      - pro_net
networks:
  pro_net:
    external: true
