# xpansync
version: "3"
services:
  xpansync:
    container_name: xpansync
    image: jovanx/xpansync
    restart: unless-stopped
    working_dir: /app
    environment:
      GOPROXY: https://goproxy.cn
      # apollo properties config relative
      APOLLO_CONFIG_APPID: xpansync
      APOLLO_CONFIG_CLUSTER: pro
      APOLLO_CONFIG_ADDR: http://apollo-pro-config-service:8080
      APOLLO_CONFIG_NAMESPACE: application
    ports:
      - 1425:1425
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib:/var/lib
    entrypoint: /app/xpansync
    tty: true
    networks:
      - apolloconfig
    
networks:
  apolloconfig:
    name: apollo_default
    external: true
